name: React Native Android CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: ikhsaan/rn-container:1.0
    steps:
    - uses: actions/checkout@v2
    - name: Envinfo
      run: npx envinfo
    - name: Package install
      run: yarn install --frozen-lockfile --prefer-offline

    - name: Grant execute permission for gradlew
      run: cd android && chmod +x gradlew
    - name: Build with Gradle
      run: cd android && ./gradlew --stacktrace assembleRelease
    - name: Get apk name & set to the env
      run: echo "OUTPUT_APK=$(ls android/app/build/outputs/apk/release/*.apk)" >> $GITHUB_ENV
    - name: Send apk to Telegram group
      env:
        BOT_TOKEN: ${{secrets.BOT_TOKEN}} 
        CHAT_ID: ${{secrets.CHAT_ID}} 
      run: curl -F chat_id="$CHAT_ID" -F document=@"${{env.OUTPUT_APK}}" "https://api.telegram.org/bot$BOT_TOKEN/sendDocument" 
