name: React Native Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: ikhsaan/rn-container:1.0
    steps:
    - uses: actions/checkout@v2
    - name: Envinfo
      run: npx envinfo
    - name: Package install
      run: yarn install --frozen-lockfile --prefer-offline

    - name: Grant execute permission for gradlew
      run: cd android && chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew --stacktrace assembleRelease
